### ISSUE TITLE
./setup.sh: line 80: [: /home/user/Program: binary operator expected error: banner not Found... 

### ISSUE THREAD

**Issue by rafidalhaque** [Gictorbit/illustratorCClinux#14]
Hello @Gictorbit,
When I run the ```./setup.sh``` command. It shows me the error below:
```bash
./setup.sh: line 80: [: /home/user/Program: binary operator expected
error: banner not Found...
```

How can I fix it, please?

**Operating System:** Manjaro XFCE 21.0.7
**Kernel:** Linux 5.10.42-1

Regards.

**Comment by DevaZikrullah** [comment]
how to fix it ?
