### ISSUE TITLE
Tiny menu

### ISSUE THREAD

**Issue by phobienbuon** [Gictorbit/illustratorCClinux#4]
Does anyone has problem with 4K screen after install the meny is tiny but no option to change.
pls help?

**Comment by Gictorbit** [comment]
You can change the resolution in `winecfg` windows, I think it could solve the problem. to do that just use option 3 provided in the script menu
![image](https://user-images.githubusercontent.com/34630603/111112169-f0590b00-8574-11eb-8563-ba8c542f858d.png)

**Comment by phobienbuon** [comment]
Hi Dictorbit. it Does not work for me

**Comment by Gictorbit** [comment]
Ok so this is because of wine and I can't fix it
